### ISSUE TITLE
download the rig

### ISSUE THREAD

**Issue by Geczy** [BarryCarlyon/twitch_developerrig_manifester#46]
where can i download it? seems twitch removed it from github

**Comment by BarryCarlyon** [comment]
The Rig is deprecated so this tool exists for those that still have the rig so they can continue.

The Rig isn't the most optimal version to do Twitch Extension Development.

**Comment by BarryCarlyon** [comment]
Using the Twtich Website (version wasn't the right word I should of said method)

**Comment by Geczy** [comment]
so there's no way to do it locally anymore? i have to start a live stream each time to test?

**Comment by BarryCarlyon** [comment]
Correct that is the most optimal way to do it inside the "real" twitch environement.
